default:
	echo 'No compilation needed'
run1:
	python3 main.py 1
run2:
	python3 main.py 2
run3:
	python3 main.py 3
run4:
	python3 main.py 4
run5A:
	python3 main.py 5A
run5B:
	python3 main.py 5B
run6:
	python3 main.py 6
run7A:
	python3 main.py 7A
run7B:
	python3 main.py 7B
runmultiple:
	python3 main.py multipleinput "${tasks}" "${m}" "${n}" "${h}" "${testcases}" "${task}" "${maxDiff}"
runsingle:
	python3 main.py singleinput "${taska}" "${taskb}" "${m}" "${n}" "${h}" "${task}" "${maxDiff}"
rungentest:
	python3 main.py generatetestcases "${m}" "${n}" "${h}" "${testcases}" "${task}" "${maxDiff}"
runfromtestfile:
	python3 main.py runfromtestfile "${tasks}" "${filename}"
runplotoutput:
	python3 main.py plotoutput "${xaxis}" "${yaxis}" "${xlabel}" "${ylabel}" "${filename}" "${foldername}" "${tasks}"
rungentable:
	python3 main.py rungentable "${filename}" "${foldername}" "${tasks}" "${testcases}"