run1: main.py, TASK1.py, TASK2.py, TASK3.py, TASK4.py
	python main.py 1
run2: main.py, TASK1.py, TASK2.py, TASK3.py, TASK4.py
	python main.py 2
run3: main.py, TASK1.py, TASK2.py, TASK3.py, TASK4.py
	python main.py 3
run4: main.py, TASK1.py, TASK2.py, TASK3.py, TASK4.py
	python main.py 4