run1:
	python3 main.py 1
run2:
	python3 main.py 2
run3:
	python3 main.py 3
run4:
	python3 main.py 4
run5:
	python3 main.py 5
runmultiple:
	python3 main.py multipleinput ${tasks} ${minval} ${maxval} ${testcases}
runsingle:
	python3 main.py singleinput ${taska} ${taskb}
rungentest:
	python3 main.py generatetestcases ${minval} ${maxval} ${testcases}
runfromtestfile:
	python3 main.py runfromtestfile ${tasks} ${filename}
runplotoutput:
	python3 main.py plotoutput ${xaxis} ${yaxis} ${xlabel} ${ylabel} ${filename}