run1:
	python3 main.py 1
run2:
	python3 main.py 2
run3:
	python3 main.py 3
run4:
	python3 main.py 4
run5:
	python3 main.py 5
runmultiple:
	python3 main.py multipleinput ${taska} ${taskb} ${minval} ${maxval}
runsingle:
	python3 main.py singleinput ${taska} ${taskb}